### ISSUE TITLE
"notify" drops previous listeners when a new one connects

### ISSUE THREAD

**Issue by paullessing** [edconolly/angular2-flux#1]
The way the Observables are set up in [Dispatcher#18-20](https://github.com/edconolly/angular2-flux/blob/master/src/app/Dispatcher.ts#L18) and [HeroesStore#17-19](https://github.com/edconolly/angular2-flux/blob/master/src/app/HeroesStore.ts#L17) only ever allows a single listener on the observables. Since on every new subscriber connection the `notify` object is overwritten, only the latest connected subscriber will get updates.

In this example this is not a problem since there is only ever one subscriber per observable, but when more than one subscriber is listening to e.g. the Dispatcher, or the Store, this pattern does not work. The `notify` method has to be replaced with either a list of listeners, or the observable should be replaced with a `Subject` on which we can call `.next()` and which automatically handles connections and notification.

I'm mentioning this because I spent an hour yesterday trying to debug why my listeners weren't being called when I used this pattern, and want to avoid others having the same problem...

**Comment by edconolly** [comment]
Have tested and can replicate. I've got a fix using Subjects instead, just need to update the docs + blog.
